/** @type {import('tailwindcss').Config} */
module.exports = {
  corePlugins: {
    preflight: false,
  },
  content: [
    "./site/components/**/*.php",
    "./site/components/**/*.js",
    "./site/templates/**/*.php",
    "./site/snippets/**/*.php",
    "./public/content/**/*.txt",
    "./public/content/**/*.json",
    "./public/index.php",
    "./index.php",
  ],
  theme: {
    extend: {
      colors: {
        prim: 'var(--color-prim, #ED1359)',
        sec: 'var(--color-sec, #EDECE7)',
        acc: 'var(--color-acc, #ED1359)',
        light: 'var(--color-light, #EDECE7)',
        dark: 'var(--color-dark, #000000)',
        text: 'var(--color-text, #151314)',
        invert: 'var(--color-invert, #FFFFFF)',
        neon: '#f4ee32',
        lime: '#ddf432',
        yellow: '#f4cd32',
        orange: '#f49a32',
        red: '#db6b57',
        crimson: '#db5f7e',
        pink: '#d56ff7',
        purple: '#986ff7',
        blue: '#034dbc',
        marine: '#7fc2db',
        cyan: '#11b5bb',
      },
      fontFamily: {
        heading: ['var(--ff-heading)', 'sans-serif'],
        body: ['var(--ff-body)', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'xs': 'calc(var(--output-size, 1rem) * 0.8)',
        's': 'calc(var(--output-size, 1rem) * 0.9)',
        'small': 'var(--font-size-small)',
        'default': 'var(--font-size-default)',
        'large': 'var(--font-size-large)',
        '1': 'var(--font-size-1)',
        '2': 'var(--font-size-2)',
        '3': 'var(--font-size-3)',
        '4': 'var(--font-size-4)',
        '5': 'var(--font-size-5)',
      },
      spacing: {
        '01': 'calc(0.1 * var(--spacing))',
        '02': 'calc(0.2 * var(--spacing))',
        '03': 'calc(0.3 * var(--spacing))',
        '05': 'calc(0.5 * var(--spacing))',
        '1': 'calc(1 * var(--spacing))',
        '2': 'calc(2 * var(--spacing))',
        '3': 'calc(3 * var(--spacing))',
        '4': 'calc(4 * var(--spacing))',
        '5': 'calc(5 * var(--spacing))',
        '6': 'calc(6 * var(--spacing))',
        '8': 'calc(8 * var(--spacing))',
        '10': 'calc(10 * var(--spacing))',
      },
      opacity: {
        '2': '0.2',
        '4': '0.4',
        '5': '0.5',
        '6': '0.6',
        '8': '0.8',
      },
      borderRadius: {
        'img': 'calc(var(--img-radius, 0.75) * 1em)',
        'radius': 'calc(var(--radius, 1.5) * 1em)',
      },
      screens: {
        'mobile': {'max': '768px'},
      }
    },
  },
  plugins: [],
}
