title: Site
columns:
  main:
    width: 2/3
    sections:
      pages:
        type: pages
        headline: StrĂˇnky
        create: default
  sidebar:
    width: 1/3
    sections:
      site_info:
        type: fields
        headline: NastavenĂ­ webu
        fields:
          site_title:
            label: NĂˇzev projektu
            type: text
          site_description:
            label: Popis webu
            type: textarea
            buttons: false
      files:
        type: files
        headline: GlobĂˇlnĂ­ soubory
