title: Stránka
columns:
  main:
    width: 2/3
    fields:
      text:
        label: Text stránky
        type: blocks
  sidebar:
    width: 1/3
    sections:
      files:
        type: files
        headline: Soubory
